spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fornecedor
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
